### ISSUE TITLE
训练速度的疑惑

### ISSUE THREAD

**Issue by codediyi** [nancheng58/Rec-Mamba#1]
我在同等条件下，训练SASRec和recmamba。batch_size设为32。执行一个step，SASRec的时间为0.007s左右；而recmamba的时间为0.34s左右。recmamba速度慢了太多，这是什么原因呢？

**Comment by nancheng58** [comment]
请问是跑的哪个数据集呀

**Comment by codediyi** [comment]
> 请问是跑的哪个数据集呀

这个问题已经解决了，是我配置环境出了问题！
