### ISSUE TITLE
是否可以提供数据

### ISSUE THREAD

**Issue by codediyi** [nancheng58/Rec-Mamba#2]
是否可以提供处理后的数据？我下载数据处理后，无法得到您提供的数据情况，平均交互长度达不到1000

**Comment by nancheng58** [comment]
请问是哪个数据集呢

**Comment by codediyi** [comment]
> 请问是哪个数据集呢
KuaiRec 数据集，我自己处理后的数据，#avg.len 并不是 11811，是否可以提供您所使用的avg.len为11,811的数据集。

**Comment by nancheng58** [comment]
抱歉，之前上传的是处理track数据集的代码，处理KuaiRec 数据集的代码刚刚上传，地址为https://github.com/nancheng58/RecMamba/blob/main/data/data_process_kuairec.py
